### ISSUE TITLE
manually request includes

### ISSUE THREAD

**Issue by hootlex** [Cyvelnet/laravel5-fractal#10]
Is there a way to manually include relations?
for example: `Fractal::item($book, new BookTransformer)0>include('author')->responseJson();`

**Comment by Cyvelnet** [comment]
yes, manual includes are supported, you may do
`Fractal::includes(['author', 'foo', 'bar'])->item($book, new BookTransformer)->responseJson()`

**Comment by hootlex** [comment]
awesome
