### ISSUE TITLE
Remove "data" on collection

### ISSUE THREAD

**Issue by stefensuhat** [Cyvelnet/laravel5-fractal#11]
Hi,

Is there anyway to remove 'data' namespace at output collection?

```
 {"code":"200","results":{"data":[{"id":"1","name":"Cafe","logo":null,"cover":""},    {"id":"2","name":"SPA","logo":null,"cover":""},{"id":"3","name":"Hotel","logo":null,"cover":""}]}}
```

My Code:

```
 $result = Fractal::collection($lists, new CategoryTransformer(), 'results')->getArray();

 return (['code' => "200", $result]);
```

Thanks.

**Comment by Cyvelnet** [comment]
Hi @ssuhat 
from your sample output, i'm thinking you would like to use the key `results` over `data` right ?

if so, you may pass your desired key as the third parameter as below.

`Fractal::collection($yourData, new YourTransformers, 'results');`

**Comment by stefensuhat** [comment]
Hi,

I've tried your suggestion it gives me

```
  {"code":"200","0":{"results":[{"id":"1","name":"Cafe","logo":"","cover":""},{"id":"2","name":"SPA","logo":"","cover":""},{"id":"3","name":"Hotel","logo":"","cover":""}]}}
```

There is "0" leading it. how can i remove it? or how can i not adding any additional "data" or "0"?

**Comment by stefensuhat** [comment]
I've seen your config there is serializer method. 

Can you guide me how to use it?

i've tried to use it but keep returning me error.

**Comment by Cyvelnet** [comment]
@ssuhat mind to share your data before transform ?

**Comment by Cyvelnet** [comment]
@ssuhat 

`array_merge(['code' => "200"],$result)`;

will solve your problem

**Comment by stefensuhat** [comment]
Hi. Thanks for helping me .

Worked great your solution using array_merge!

I've use $result = ['code'=> "200"] + $result; right now. 
but will change to your solution. make more sense to read. lol!

**Comment by RAMMELEKE** [comment]
Hello Cyvelnet, I tried using fractal transformer but then the collection has "data" namespace... how can i totally remove it from the collection... i want basic json output format

**Comment by Cyvelnet** [comment]
@RAMMELEKE to remove the data namespace, you may extends League\Fractal\Serializer\ArraySerializer to overrides collections method

then update `serializer`  section in `/config/fractal.php` to use your custom serializer instead
