### ISSUE TITLE
Parse Includes

### ISSUE THREAD

**Issue by stefensuhat** [Cyvelnet/laravel5-fractal#13]
Hi, I've like your package so much. make fractal a lot easier. I want to ask if the parseIncludes method is available?

I've tried 

```
$results = Fractal::collection($exp, new ExperienceTransformer(), 'results')->includes(['user'])->getArray();
```

got an error

```
 Call to undefined method Cyvelnet\Laravel5Fractal\Adapters\ScopeDataAdapter::includes()
```

I've already put user under '$availableIncludes' method
Is there anyway to use parseIncludes?

**Comment by hootlex** [comment]
Try:
`
Fractal::includes(['user'])->collection($exp, new ExperienceTransformer(), 'results')->getArray()
`

**Comment by stefensuhat** [comment]
Works perfectly! . Thanks
