### ISSUE TITLE
Laravel 5.2 Support?

### ISSUE THREAD

**Issue by ghost** [Cyvelnet/laravel5-fractal#14]
- cyvelnet/laravel5-fractal dev-master requires illuminate/support 5.0.x|5.1.x -> satisfiable by laravel/framework[v5.1.27], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
- Conclusion: don't install laravel/framework v5.2.1

**Comment by Cyvelnet** [comment]
@azcoppen  5.2 is now supported, kindly switch version to 1.3.*

**Comment by ghost** [comment]
Amazingly fast - thank you!
