### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by stefensuhat** [Cyvelnet/laravel5-fractal#15]
Will you release Laravel 5.2 version?. Because it's still error when i try to require it

Thanks

**Comment by Cyvelnet** [comment]
@ssuhat might to post the errors? Btw are u on version 1.3 ?

**Comment by stefensuhat** [comment]
Yes. I do fresh install. Here is the error

**Comment by Cyvelnet** [comment]
@ssuhat did you have other packages dealing with fractal transformer? based on the errors output, you have another package required 'league/fractal' with a version of 0.13.0 where laravel5-fractal currently ship with 'league/fractal' 0.12.*

opt 1: you may remove 'league/fractal' from ur composer.json, laravel5-fractal will require support version for you
opt2 : install laravel5-fractal: dev-master (support league/fractal 0.13) to verify if ur problem resolved.

**Comment by stefensuhat** [comment]
Thanks @Cyvelnet.. 
It's working now. I use dev-master branch.
