### ISSUE TITLE
Cannot set custom key for includes item

### ISSUE THREAD

**Issue by stefensuhat** [Cyvelnet/laravel5-fractal#18]
Hi

I've tried change the key result for item but it keep returning me the include name:

```
// TransactionTransformer
protected $defaultIncludes = ['user_alternative'];
public function transform($resource)
{
    return [
        'id'            => $resource->id,
        'name'          => $resource->name,
        'location_name' => $resource->location_name,
    ];
}

public function includeUserAlternative($resource)
{
    $resource = $resource->user;

    return $this->item($resource, new UserAlternativeTransformer, 'user');
}
```

But it still return me like this:

```
  {
    "transactions": [
    {
      "id": "C-1459134734-aWL6K",
      "amount": 57066,
      "transaction_date": "2016-03-01",
      "user_alternative": {
          "id": "B015f6c48c43b7494",
          "name": "John DOe",
      }
    },
    {
      "id": "C-12311512-aWL6K",
      "amount": 131231,
      "transaction_date": "2016-03-01",
      "user_alternative": {
          "id": "B015f6c48c43b7494",
          "name": "John DOe",
      }
    }
    ]
  }
```

Is it a bug ? or this is exactly how includes work?.
How can I change the user_alternative key to user?

**Comment by Cyvelnet** [comment]
@ssuhat this is an intended behavior when you transform a single record(not collection), the dependency `league/fractal` will ignore the resourceKey when you use the method `item`

is there any reason, you choose `user_alternative` over `user` ? since it is a default includes, it is expected to stay consistent across every resource.

**Comment by stefensuhat** [comment]
@Cyvelnet Hi, because I already have UserTransformer and I need a shorter result. Thats why I make user alternative.

Oh i see. Looks like i need to find another way. Thanks

**Comment by Cyvelnet** [comment]
@ssuhat then just as a workaround, you do this way,

`public function transform($resource)
    {

```
   return [
    'id'            => $resource->id,
    'amount'          => $resource->amount,
    'transaction_date' => $resource->transaction_date,
    'user' => app('fractal')->item($resource->user, new UserAlternativeTransformer())->getArray()
];
}`
```

and remove the default includes, you will get your desired result,

with this, you have selected any key you wished, and bind with a transformed array data

**Comment by stefensuhat** [comment]
Wow. awesome!. Wil try it when I get home.
