### ISSUE TITLE
method collection marked as @internal

### ISSUE THREAD

**Issue by isaackearl** [Cyvelnet/laravel5-fractal#2]
I'm using phpstorm as my ide and when I use Fractal::collection it crosses it out as an indication that it is marked as @internal (phpdoc) and that I shouldn't use it.  Still works but is bothersome.

**Comment by isaackearl** [comment]
I will say as a side note, that I really like your laravel package.  Looking forward to seeing it evolve etc.

**Comment by Cyvelnet** [comment]
oops, my bad for not removing that and glad to know that you like it :)
