### ISSUE TITLE
Cant use with laravel 5.3

### ISSUE THREAD

**Issue by pderiy** [Cyvelnet/laravel5-fractal#22]
![image](https://cloud.githubusercontent.com/assets/9549383/17562839/ef4b345e-5f2c-11e6-9397-190fe3c136af.png)

Can your fix illuminate/support version dependencies?

**Comment by Cyvelnet** [comment]
@edomos thx for PR [23287e2](https://github.com/Cyvelnet/laravel5-fractal/commit/23287e21dfdee9c1ac77e836751033a18eb5f86c)
