### ISSUE TITLE
[suggestion] provides a way to return json response 

### ISSUE THREAD

**Issue by terrylow** [Cyvelnet/laravel5-fractal#3]
currently i have to write

return Response::json(Fractal::collection($user, new UserTransformer));

if provides a way to return data as following
$http_status = 200;
return Fractal::collection($user, new UserTransformer))->responseJson($http_status);

it look so much elegant this way

**Comment by Cyvelnet** [comment]
hi, good catch, you have that a go, already included that features in the last commit

now you do that ->responseJson($http_status, $header);
and also if you like to get the transformed array you may do something like

$userCollectoin = Fractal::collection($user, new UserTransformer))->getArray();
