### ISSUE TITLE
How do I insert data to the meta?

### ISSUE THREAD

**Issue by sharenjoy** [Cyvelnet/laravel5-fractal#4]
How do I insert data to the meta?
It will look like this.

```
{
  "data": {}
  "meta": {
    "rules_failed": {
      "firstname": [
        "The firstname field is required."
      ]
    }
  }
}
```

thanks

**Comment by Cyvelnet** [comment]
validation errors should have to handled before the transformations are hits, just like the common application behaviors

but for a suggestion, you may do 

`if ($e instanceOf ValidationException) {
     return // format your validation message here
}`

in your App\Exception\Handler file
and this logic wrote only once.
