### ISSUE TITLE
Include param not populating scope

### ISSUE THREAD

**Issue by brodkin** [Cyvelnet/laravel5-fractal#8]
I may just be doing something incorrectly here, but I'm running Laravel 5.1 and setting `include=email` as a query param for a GET request, but `includeEmail()` is not being triggered. If I put `email` into my `$defaultIncludes` on the transformer it works as expected, but not via query var. Any insight?

**Comment by Cyvelnet** [comment]
@brodkin  did you have autoload set to true in `config\fractal`? autoload includes are disabled by default, if there is not `fractal.php` in config directory you might want to publish vendor config with `php artisan vendor:publish`

**Comment by brodkin** [comment]
That was totally it--I had published it, but forgot to change that setting. Thanks!

**Comment by hootlex** [comment]
very useful info, consider adding it to the docs
